accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts import views

urlpatterns = [
    path("send_login_email", views.send_login_email, name="send_login_email"),
    path("login", views.login, name="login"),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
]

lists/urls.py
from django.urls import path

from lists import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", views.home_page, name="home_page"),
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("users/<str:email>/", views.my_lists, name="my_lists"),
    path("public_lists/", views.public_lists, name="public_lists"),
]

superlists/urls.py
from django.urls import path, include

from accounts import urls as accounts_urls
from lists import urls as list_urls
from lists import views as list_views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", list_views.home_page, name="home"),
    path("lists/", include(list_urls)),
    path("accounts/", include(accounts_urls)),
]

accounts/models.py
import uuid

from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models


class User(models.Model):
    email = models.EmailField(primary_key=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
# Create your models here.
from django.conf import settings
from django.db import models
from django.urls import reverse


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import models

from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.fields.TextInput(
                attrs={
                    "placeholder": "Buy milk",
                    "class": "form-control input-lg",
                    "autofocus": True,
                    "onfocus": "this.select()",
                    "title": "Type something then hit 'Enter' to add it to the list",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data["text"], owner=owner
            )
        else:
            return List.create_new(first_item_text=self.cleaned_data["text"])


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib import auth, messages
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    email = request.POST["email"]
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(reverse("login") + "?token=" + str(token.uid))
    message_body = (
        f"Here's your personal login link:\n{url}\n"
        # f"Use this link whenever you want to sign in, "
        # f"maybe add it to your browser's bookmarks."
    )
    send_mail(
        "Your login link for Superlists",
        message_body,
        "noreply@superlists",
        [email],
    )
    messages.success(
        request, "Check your email, we've sent you a link you can use to log in."
    )
    return redirect("/")


def login(request):
    user = auth.authenticate(uid=request.GET.get("token"))
    if user:
        auth.login(request, user)
    return redirect("/")

lists/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import redirect, render

from lists.forms import ExistingListItemForm, ItemForm, NewListForm
from lists.models import List

User = get_user_model()


def home_page(request):
    return render(request, "home.html", {"form": ItemForm()})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, "home.html", {"form": form})


def view_list(request, list_id):
    try:
        list_ = List.objects.get(id=list_id)
    except List.DoesNotExist:
        return HttpResponseNotFound(f"Error: Can't find list {list_id}...")
    if list_.owner is not None and list_.owner != request.user:
        return HttpResponseForbidden(
            "Error: That's not your list, or you're not logged in."
        )
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "list.html", {"list": list_, "form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", {"owner": owner})


def public_lists(request):
    lists = List.objects.filter(owner=None)
    return render(request, "public_lists.html", {"lists": lists})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super To-Do Lists</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'Fira_Code_v6.2/fira_code.css' %}">
</head>

<body>
<div class="main">
    <nav class="navbar" role="navigation">
        <ul class="nav">
            <li class="brand"><a href="/" title="Go to the homepage to start a new To-Do list ">Superlists</a></li>
            <li>🤌</li>
            <li class="header" id="id_header">{% block header_text %}{% endblock %}</li>
            <li class="nav-link">View all lists:</li>
            <li class="nav-link"><a href="{% url 'public_lists' %}">Public</a></li>
            <li class="nav-link">
                <div class="user">
                    {% if user.email %}
                        <div class="already-logged-in">
                            <ul>
                                <li class="nav"><a href="{% url 'my_lists' user.email %}" title="View your To-Do lists">Personal</a></li>
                                <li class="nav"><a href="{% url 'logout' %}" title="Logout and go to the home page">Logout ({{ user.email }})</a></li>
                            </ul>
                        </div>
                    {% else %}

                        <div class="login-form">
                            <form id="id_login_form" class="form-login" method="POST"
                                  action="{% url 'send_login_email' %}">
                                {% csrf_token %}
                                <label for="email">Enter email to log in:
                                    <input class="form-control" id="id_email_input" name="email" type="text"
                                           placeholder="user@example.com" title="We'll send you an email with a personal login link"/>
                                </label>
                            </form>
                        </div>

                    {% endif %}
                    {% if not messages and not user.email %}
                        <div id="id_login_button"><a href="#" title="Login so you can save and come back to your lists">Personal</a></div>
                    {% elif messages %}
                        <div class="messages">
                            {% for message in messages %}
                                {% if message.level_tag == 'success' %}
                                    <div class="message message-success">
                                        {{ message }}
                                    </div>
                                {% else %}
                                    <div class="message message-warning">
                                        {{ message }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        {#                        <a id="id_close_button" href="#">close</a>#}
                    {% endif %}
                </div>
            </li>
        </ul>


    </nav>
    {% block list_form %}
        <div class="form">
            <form class="form-todo" method="POST" action="{% block form_action %}{% endblock %}">
                {% csrf_token %}
                <label for="text">Enter a to-do item: {{ form.text }}</label>
                {% if form.errors %}
                    <div class="form-group has-error">
                        <div class="help-block">{{ form.text.errors }}</div>
                    </div>
                {% endif %}
            </form>
        </div>
    {% endblock %}
    {% block table %}{% endblock %}
    {% block extra_content %}{% endblock %}
</div>
<footer>
    <div class="f_left">
        <div class="f_item">
            🤙 davidlpoole
            <script>document.write(new Date().getFullYear())</script>
        </div>
    </div>
    <div class="f_right">
        <div class="f_item">
            <a href="https://github.com/davidlpoole/">👉 Go to my GitHub profile </a>
        </div>
        <div class="f_item">
            <a href="https://github.com/davidlpoole/obeythetestinggoat">👉 Go to this specific repo </a>
        </div>
    </div>
</footer>
</body>

<script src="/static/jquery-3.7.0.min.js"></script>
<script src="/static/lists.js"></script>
<script>
    $(document).ready(function () {
        window.Superlists.initialize();
    });
</script>
<script>
    $(document).ready(function () {
        $("#id_login_button").click(function () {
            $(".login-form").show();
            $("#id_login_button").hide();
            $("#id_close_button").show();
            $("#id_email_input").focus()
        });
        $("#id_close_button").click(function () {
            $(".messages").hide();
            $("#id_close_button").hide();
            $("#id_login_button").show();
            {#$(".login-form").show();#}
            {#$("#id_email_input").focus()#}
        });
        $("#id_email_input").focusout(function () {
            {#$(".messages").hide();#}
            {#$("#id_close_button").hide();#}
            $("#id_login_button").show();
            $(".login-form").hide();
            {#$("#id_email_input").focus()#}
        });
    });
</script>
<script>

</script>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}
    Start a new {% if user.email %}personal{% else %}<span title="Login to create a personal list 👉">public</span>{% endif %} To-Do list
{% endblock %}

{% block form_action %}
    {% url 'new_list' %}
{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}
    Your To-Do list
{% endblock %}

{% block form_action %}
    {% url 'view_list' list.id %}
{% endblock %}

{% block table %}
    <div class="table">
        <table class="list_table" id="id_list_table">
            {% for item in list.item_set.all %}
                <tr>
                    <td class="counter">
                        {{ forloop.counter }}:
                    </td>
                    <td class="item_text">
                        {{ item.text }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}
    My Lists
{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <div class="extra-content">
{#        <div>{{ owner.email }}'s lists:</div>#}
        <ul class="list_links">
            {% for list in owner.list_set.all %}
                <li class="list_link"><a href="{{ list.get_absolute_url }}" title='Go to the list named "{{ list.name }}"'>{{ list.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

lists/templates/public_lists.html
{% extends 'base.html' %}

{% block header_text %}
    Public Lists
{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <div class="extra-content">
{#        <div>Public lists:</div>#}
        <ul class="list_links">
            {% for list in lists.all %}
                <li class="list_link"><a href="{{ list.get_absolute_url }}" title='Go to the list named "{{ list.name }}"'>{{ list.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}